substitutions:
  name: "s31"
  friendly_name: "Sonoff S31"
  hidden_ssid: "false"
  log_level: DEBUG

esp8266:
  board: esp12e
  early_pin_init: False
  restore_from_flash: True

packages:
  device_base: !include common/base.yaml
  s31_configs: !include static/s31.yaml
