esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project:
    name: calabresemic.esphome
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:

http_request:
  verify_ssl: false

api:

ota:
  - platform: esphome
    id: ota_esphome

wifi:

button:
  - platform: restart
    name: Restart

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: Uptime
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

time:
  - platform: homeassistant
    id: my_time
