esp8266:
  board: esp01_1m
  restore_from_flash: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO13
    inverted: True

switch:
  - platform: gpio
    name: Relay
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

uart:
  rx_pin: RX
  baud_rate: 4800
